# Make-readable projection of config/scenarios/nonempirical.tsv.
# Keep values synchronized with the TSV scenario manifest.

REFERENCE_DATASETS ?= yeast_small,moderate_genome,sockeye_reference,trichoderma_reference
EMPIRICAL_DATASETS ?= sockeye_ddrad,trichoderma_ddrad
MATCHED_REFERENCE ?= data/reference/yeast.fa.gz
MATCHED_DATASET ?= yeast_small
MATCHED_CONDITION ?= B1
MATCHED_ENZYMES ?= EcoRI,MseI
MATCHED_ENZYME_PAIR_LABEL ?= EcoRI+MseI
MATCHED_MIN_SIZE ?= 100
MATCHED_MAX_SIZE ?= 300
MATCHED_RUNS ?= 5
DIGEST_COMPARISON_REFERENCE ?= data/reference/yeast.fa
DIGEST_COMPARISON_DATASET ?= yeast_small_plain
DIGEST_COMPARISON_CONDITION ?= B1
DIGITAL_RADS_PATH ?= external/Digital_RADs/Digital_RADs.py
DDGRADER_REPO ?= external/ddRadSeqWebTool
SIMRAD_WARM_REFERENCE ?= data/reference/yeast.fa.gz
SCREENING_REFERENCE ?= data/reference/yeast.fa
SCREENING_DATASET ?= yeast_small_plain
SCREENING_ENZYMES ?= config/candidate_enzymes.txt
SCREENING_MIN_SIZE ?= 300
SCREENING_MAX_SIZE ?= 600
SCREENING_SCORE_MIN ?= 1
SCREENING_SCORE_MAX ?= 2000
SCREENING_SIZE_MODEL ?= hard
SCREENING_RUNS ?= 5
SCREENING_JOBS ?= 2
SCREENING_RADIGEST_THREADS ?= 1
INPUT_FORMAT_WORKFLOW_CONFIG ?= workflow/config.yeast_input_formats.yml
MODERATE_PLAIN_REF ?= data/reference/moderate.fa
SCALING_DATASET ?= cannabis_pink_pepper_plain
SCALING_SNAKEMAKE_CORES ?= 1
THREAD_SCALING_CONDITIONS ?= B1,B2
THREAD_SCALING_MODES ?= json,fragments_tsv
THREAD_SCALING_THREADS ?= 1,2,4,8
THREAD_SCALING_RUNS ?= 7
PAIR_SCREEN_STEM_PREFIX ?= cannabis
PAIR_SCREEN_ENZYMES ?= config/candidate_enzymes.txt
PAIR_SCREEN_MIN_SIZE ?= 300
PAIR_SCREEN_MAX_SIZE ?= 600
PAIR_SCREEN_SCORE_MIN ?= 1
PAIR_SCREEN_SCORE_MAX ?= 2000
PAIR_SCREEN_SIZE_MODEL ?= hard
PAIR_SCREEN_RUNS ?= 3
PAIR_SCREEN_JOBS ?= 1 2 4 8
PAIR_SCREEN_RADIGEST_THREADS ?= 1

# Backward-compatible variable names used by existing Make targets.
YEAST_PLAIN_REF ?= $(DIGEST_COMPARISON_REFERENCE)
YEAST_PLAIN_DATASET ?= $(DIGEST_COMPARISON_DATASET)
YEAST_CONDITION ?= $(DIGEST_COMPARISON_CONDITION)
SCALING_MODES ?= $(THREAD_SCALING_MODES)
SCALING_THREADS_LIST ?= $(THREAD_SCALING_THREADS)
