#!/usr/bin/env python3
"""Phase 1 repository polish for radigest comparison workflows.

This script is intentionally conservative. It does not move scripts, rewrite
Snakefiles, rename datasets, or touch generated results.

It can:
  1. back up touched files;
  2. deduplicate duplicate Makefile target blocks, keeping the last definition;
  3. rewrite .gitignore to a single canonical version;
  4. write docs/output_contracts.md;
  5. write docs/release_checklist.md.

Default mode is dry-run. Use --apply to modify files.

Example:
  python3 scripts/phase1_polish_repository.py
  python3 scripts/phase1_polish_repository.py --apply
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
from pathlib import Path

CANONICAL_GITIGNORE = """# Large reference and empirical data are excluded from Git.
data/reference/*
data/empirical/*
!data/reference/.gitkeep
!data/empirical/.gitkeep

# Raw genome/read/alignment data.
*.fasta
*.fna
*.fa.gz
*.fasta.gz
*.fna.gz
*.fastq
*.fastq.gz
*.fq
*.fq.gz
*.bam
*.sam
*.cram
*.bai
*.crai

# Allow committed synthetic validation FASTA files.
!data/synthetic/
!data/synthetic/*.fa
!data/synthetic/*.fasta
!data/synthetic/*.fna

# External comparator checkouts.
external/*
!external/.gitkeep

# Raw workflow, benchmark, and processed outputs.
results/raw/*
results/processed/*
results/tables/*
results/figures/*
benchmark/time/*
benchmark/memory/*
benchmark/logs/*
!results/raw/.gitkeep
!results/processed/.gitkeep
!results/tables/.gitkeep
!results/figures/.gitkeep
!benchmark/time/.gitkeep
!benchmark/memory/.gitkeep
!benchmark/logs/.gitkeep

# Manuscript exports.
# Final curated artifacts can be force-added with git add -f.
manuscript_tables/*
manuscript_figures/*
!manuscript_tables/.gitkeep
!manuscript_figures/.gitkeep

# Local radigest source/build checkout.
.local/

# Temporary backups written by repository polish scripts.
.phase1_backups/

# Python/R/Snakemake/cache.
.venv/
__pycache__/
.pytest_cache/
.mypy_cache/
.ruff_cache/
.Rhistory
.RData
.julia/
.snakemake/
snakemake_cache/
.conda/
.mamba/

# OS/editor.
.DS_Store
.vscode/
.idea/

# Generated codebase snapshots.
codebase.json
*codebase*
"""


OUTPUT_CONTRACTS = """# Output contracts

This repository separates raw tool output, normalized intermediate files,
analysis summaries, benchmark logs, and curated manuscript artifacts.

## Directory meanings

### `results/raw/`

Raw or minimally transformed tool outputs.

Examples:

- direct radigest JSON, GFF3, fragment TSV, and fragment FASTA outputs;
- raw comparator outputs;
- per-run screening outputs;
- manual smoke-test outputs.

These files are reproducible and should normally remain ignored by Git.

### `results/processed/`

Normalized or derived intermediate files.

Examples:

- normalized interval tables;
- validation summaries;
- reference metadata;
- empirical TLEN extraction products;
- input compatibility checks.

These files are reproducible and should normally remain ignored by Git.

### `results/tables/`

Analysis-level tables generated from `results/raw/`, `results/processed/`,
or `benchmark/`.

Examples:

- benchmark run summaries;
- matched-tool timing summaries;
- empirical recovery summaries;
- screening summaries.

These files are reproducible analysis products. They are not the curated
manuscript layer and should normally remain ignored by Git.

### `results/figures/`

Reproducible figures generated from processed files or summary tables.

These are generated outputs. They should normally remain ignored by Git unless
there is a specific reason to archive them separately.

### `benchmark/time/`

Timing files generated by benchmarking tools other than `/usr/bin/time -v`.

### `benchmark/memory/`

`/usr/bin/time -v` output files, including wall time, CPU time, exit status, and
maximum resident set size.

### `benchmark/logs/`

stdout/stderr logs from benchmarked commands and workflow jobs.

### `manuscript_tables/`

Curated final tables intended for the manuscript or supplement.

These are the only table outputs that may be intentionally tracked. Because the
directory is ignored by default, final tables should be staged explicitly:

```bash
git add -f manuscript_tables/*.tsv
```

### `manuscript_figures/`

Curated final figure exports intended for the manuscript or supplement.

These are ignored by default and should be staged explicitly only when they are
final manuscript artifacts.

## Important rule

`make manuscript-tables` is a collector. It reads existing `results/` files and
writes curated `manuscript_tables/` files. It does not rerun every upstream
analysis.

For final release, run all intended analyses first, then run:

```bash
make manuscript-tables
make audit
```

Only stage manuscript tables after confirming that required claim rows are
`present`, not `MISSING`.
"""


RELEASE_CHECKLIST = """# Release checklist

Before tagging a public release:

- [ ] `preflight` passes.
- [ ] `make check-local THREADS=1` passes, or `make check RADIGEST=<path> THREADS=1` passes.
- [ ] `make reference-data-dry-run` passes.
- [ ] `make empirical-recovery-dry-run` passes on a machine with empirical data paths configured.
- [ ] `make audit` reports no `FAIL` entries.
- [ ] Expected release-time `WARN` entries are resolved or documented.
- [ ] `CITATION.cff` has final DOI and release date after archival.
- [ ] `config/datasets.tsv` has final accessions, URLs, and SHA256 checksums where redistribution is possible.
- [ ] `config/empirical_recovery.tsv` matches the manuscript empirical windows.
- [ ] Public reference FASTA files can be downloaded with `make reference-data`.
- [ ] Empirical BAM/CRAM files are either archived externally or documented as required local inputs.
- [ ] BAM/reference compatibility checks pass for empirical recovery datasets where coordinate-level interpretation is used.
- [ ] `make manuscript-tables` was run after all intended analyses were regenerated.
- [ ] Curated manuscript tables are force-added with `git add -f manuscript_tables/*.tsv`.
- [ ] Raw FASTA, FASTQ, BAM, CRAM, external checkouts, and benchmark scratch outputs are not staged.
- [ ] The radigest source commit or release tag used for the analysis is recorded.
- [ ] The repository tag matches the Methods/Data availability text in the manuscript.

## Expected release-time warnings

The following warnings are acceptable during active development but should be
resolved before archival release:

- `CITATION.cff` DOI/date fields marked `TO_BE_FILLED`;
- public or empirical data accessions marked `TO_BE_FILLED`;
- expected SHA256 checksums marked `TO_BE_FILLED`.

## Files that should normally not be tracked

- `data/reference/*`
- `data/empirical/*`
- `external/*`
- `results/raw/*`
- `results/processed/*`
- `results/tables/*`
- `results/figures/*`
- `benchmark/*`
- `.local/*`
- `codebase.json`
"""


TARGET_RE = re.compile(r"^([A-Za-z0-9_.-]+)\s*:(?![=])")
ASSIGNMENT_RE = re.compile(r"^[A-Za-z0-9_.-]+\s*(?::=|\?=|\+=|=)")


def require_repo_root() -> None:
    required = [
        Path("Makefile"),
        Path(".gitignore"),
        Path("config"),
        Path("scripts"),
        Path("workflow"),
    ]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        missing_text = ", ".join(missing)
        raise SystemExit(
            "This does not look like the radigest comparison repo root. "
            f"Missing: {missing_text}"
        )


def is_assignment(line: str) -> bool:
    return bool(ASSIGNMENT_RE.match(line))


def single_target_name(line: str) -> str | None:
    """Return a single Make target name if line starts a simple target block.

    This intentionally skips:
      - variable assignments;
      - special targets such as .PHONY;
      - multi-target rules;
      - indented recipe lines;
      - comments.
    """
    if not line.strip():
        return None
    if line.startswith(("\t", " ", "#")):
        return None
    if line.startswith("."):
        return None
    if is_assignment(line):
        return None
    if ":" not in line:
        return None

    before = line.split(":", 1)[0].strip()
    if " " in before:
        return None
    if "=" in before:
        return None

    match = TARGET_RE.match(line)
    if match is None:
        return None

    return match.group(1)


def is_top_level_boundary(line: str) -> bool:
    if not line.strip():
        return False
    if line.startswith(("\t", " ")):
        return False
    if line.startswith("#"):
        return False
    if line.startswith((".PHONY", "include ", "-include ")):
        return True
    if is_assignment(line):
        return True
    return single_target_name(line) is not None


def parse_target_blocks(lines: list[str]) -> list[tuple[str, int, int]]:
    """Return Makefile target blocks as (target, start_idx, end_idx)."""
    blocks: list[tuple[str, int, int]] = []
    i = 0

    while i < len(lines):
        target = single_target_name(lines[i])
        if target is None:
            i += 1
            continue

        start = i
        j = i + 1
        while j < len(lines):
            if is_top_level_boundary(lines[j]):
                break
            j += 1

        blocks.append((target, start, j))
        i = j

    return blocks


def dedupe_makefile_text(text: str) -> tuple[str, list[str]]:
    """Remove earlier duplicate simple-target blocks, keeping the last."""
    lines = text.splitlines(keepends=True)
    blocks = parse_target_blocks(lines)

    by_target: dict[str, list[tuple[str, int, int]]] = {}
    for block in blocks:
        target = block[0]
        by_target.setdefault(target, []).append(block)

    remove_ranges: list[tuple[int, int, str]] = []
    messages: list[str] = []

    for target in sorted(by_target):
        target_blocks = by_target[target]
        if len(target_blocks) <= 1:
            continue

        keep = target_blocks[-1]
        for block in target_blocks[:-1]:
            remove_ranges.append((block[1], block[2], target))

        messages.append(
            f"dedupe Makefile target {target!r}: kept line {keep[1] + 1}, "
            f"removed {len(target_blocks) - 1} earlier definition(s)"
        )

    if not remove_ranges:
        return text, ["No duplicate simple Makefile targets detected."]

    for start, end, _target in sorted(remove_ranges, reverse=True):
        del lines[start:end]

    return "".join(lines), messages


def backup_file(path: Path, backup_root: Path) -> Path | None:
    if not path.exists():
        return None

    backup_path = backup_root / path
    backup_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, backup_path)
    return backup_path


def write_if_changed(
    path: Path,
    content: str,
    apply: bool,
    backup_root: Path,
    messages: list[str],
) -> None:
    old = path.read_text() if path.exists() else None

    if old == content:
        messages.append(f"unchanged {path}")
        return

    if not apply:
        status = "would update" if path.exists() else "would create"
        messages.append(f"{status} {path}")
        return

    backup = backup_file(path, backup_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)

    if backup is None:
        messages.append(f"created {path}")
    else:
        messages.append(f"updated {path}; backup {backup}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Modify files. Without this flag, run in dry-run mode.",
    )
    args = parser.parse_args()

    require_repo_root()

    timestamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_root = Path(".phase1_backups") / timestamp

    messages: list[str] = []
    messages.append(f"mode={'APPLY' if args.apply else 'DRY-RUN'}")

    makefile_path = Path("Makefile")
    makefile_text = makefile_path.read_text()
    new_makefile_text, dedupe_messages = dedupe_makefile_text(makefile_text)
    messages.extend(dedupe_messages)

    write_if_changed(
        makefile_path,
        new_makefile_text,
        args.apply,
        backup_root,
        messages,
    )
    write_if_changed(
        Path(".gitignore"),
        CANONICAL_GITIGNORE,
        args.apply,
        backup_root,
        messages,
    )
    write_if_changed(
        Path("docs/output_contracts.md"),
        OUTPUT_CONTRACTS,
        args.apply,
        backup_root,
        messages,
    )
    write_if_changed(
        Path("docs/release_checklist.md"),
        RELEASE_CHECKLIST,
        args.apply,
        backup_root,
        messages,
    )

    print("\n".join(messages))
    if not args.apply:
        print("\nNo files were modified. Re-run with --apply to write changes.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
